- job:
    name: 'instack-ironic-deployment-full'
    description: 'Use Ironic to do full node deployment'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc; 
          DEPLOY_HEAT_TEMPLATE=/home/stack/instack-undercloud/heat-templates/ironic-deployment.yaml
          NULL_STATS=1
          CONTROL_COUNT=1
          COMPUTE_COUNT=3
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --register-nodes
          --nodes-json /home/stack/instackenv.json
          --discover-nodes
          --show-profile
          --setup-flavors
          --deploy-nodes"
- job:
    name: 'instack-ironic-deployment-registration'
    description: 'Use Ironic to do node registration'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc; 
          NULL_STATS=1
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --register-nodes
          --nodes-json /home/stack/instackenv.json"
- job:
    name: 'instack-ironic-deployment-discovery'
    description: 'Use Ironic to do node discovery'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc; 
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --discover-nodes"
- job:
    name: 'instack-ironic-deployment-deploy-only'
    description: 'Use Ironic to do node deployment only'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc; 
          DEPLOY_HEAT_TEMPLATE=/home/stack/instack-undercloud/heat-templates/ironic-deployment.yaml
          CONTROL_COUNT=1
          COMPUTE_COUNT=3
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --deploy-nodes"
- job:
    name: 'instack-ironic-deployment-show-profiles'
    description: 'Use Ironic to show assigned node profiles'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc; 
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --show-profile"
- job:
    name: 'instack-ironic-deployment-setup-flavors'
    description: 'Use Ironic to setup flavors'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc; 
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --setup-flavors"
- job:
    name: 'instack-ironic-deployment-delete-stack'
    description: 'Use Ironic to setup flavors'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc;
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --delete-stack"
- job:
    name: 'instack-ironic-deployment-delete-nodes'
    description: 'Delete all nodes'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc;
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --delete-nodes"
- job:
    name: 'instack-ironic-deployment-clean-full'
    description: 'Clean up a previous deployment and then do a full deployment'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc;
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --delete-stack
          --delete-nodes;
          DEPLOY_HEAT_TEMPLATE=/home/stack/instack-undercloud/heat-templates/ironic-deployment.yaml
          NULL_STATS=1
          CONTROL_COUNT=1
          COMPUTE_COUNT=3
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --register-nodes
          --nodes-json /home/stack/instackenv.json
          --discover-nodes
          --show-profile
          --setup-flavors
          --deploy-nodes"
- job:
    name: 'instack-ironic-deployment-config-tools-provision'
    description: 'Run config-tools provision.sh to prep for Puppet'
    project-type: freestyle
    wrappers:
      - ansicolor:
          colormap: xterm
    builders:
      - shell: >
          sudo /bin/bash -c "
          source /root/stackrc;
          /home/stack/instack-undercloud/scripts/instack-ironic-deployment -x
          --config-tools-provision"
