heat_template_version: 2014-10-16

parameters:
  flavor:
    type: string
    default: baremetal_compute

  image:
    type: string
    default: os-disk-config

  key_name:
    type: string
    default: default

  node_count:
    type: number
    default: 1

  disk_config:
    type: string
    default: {}

resources:
  disk_config_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: node_count}
      resource_def:
        type: OS::TripleO::DiskConfig
        properties:
            flavor: {get_param: flavor}
            image: {get_param: image}
            key_name: {get_param: key_name}
            disk_config: {get_param: disk_config}
