heat_template_version: 2014-10-16

description: Test os-disk-config node.  Can be wrapped in a ResourceGroup for scaling.

parameters:
  disk_config:
    default: {}
    type: string

  flavor:
    type: string
    default: baremetal_compute

  image:
    type: string
    default: os-disk-config

  key_name:
    type: string
    default: default

resources:
  DiskConfigServer:
    type: OS::Nova::Server
    properties:
        flavor: {get_param: flavor}
        image: {get_param: image}
        key_name: {get_param: key_name}
        user_data_format: SOFTWARE_CONFIG
        #name: os-disk-config%index%

  ServerConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
          os_disk_config: {get_input: disk_config}
          flavor: {get_input: flavor}
          image: {get_input: image}
          key_name: {get_input: key_name}

  ServerDeployment:
    type: OS::Heat::StructuredDeployment
    properties:
      config: {get_resource: ServerConfig}
      server: {get_resource: DiskConfigServer}
      signal_transport: NO_SIGNAL
      input_values:
        disk_config: {get_param: disk_config}
        flavor: {get_param: flavor}
        image: {get_param: image}
        key_name: {get_param: key_name}
